/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewIndexRouteImport } from './routes/preview/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as PreviewListPageRouteImport } from './routes/preview/list-page'
import { Route as PreviewDashboardRouteImport } from './routes/preview/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIndexRoute = PreviewIndexRouteImport.update({
  id: '/preview/',
  path: '/preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewListPageRoute = PreviewListPageRouteImport.update({
  id: '/preview/list-page',
  path: '/preview/list-page',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewDashboardRoute = PreviewDashboardRouteImport.update({
  id: '/preview/dashboard',
  path: '/preview/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preview/dashboard': typeof PreviewDashboardRoute
  '/preview/list-page': typeof PreviewListPageRoute
  '/customers/': typeof CustomersIndexRoute
  '/preview/': typeof PreviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview/dashboard': typeof PreviewDashboardRoute
  '/preview/list-page': typeof PreviewListPageRoute
  '/customers': typeof CustomersIndexRoute
  '/preview': typeof PreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preview/dashboard': typeof PreviewDashboardRoute
  '/preview/list-page': typeof PreviewListPageRoute
  '/customers/': typeof CustomersIndexRoute
  '/preview/': typeof PreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preview/dashboard'
    | '/preview/list-page'
    | '/customers/'
    | '/preview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview/dashboard'
    | '/preview/list-page'
    | '/customers'
    | '/preview'
  id:
    | '__root__'
    | '/'
    | '/preview/dashboard'
    | '/preview/list-page'
    | '/customers/'
    | '/preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreviewDashboardRoute: typeof PreviewDashboardRoute
  PreviewListPageRoute: typeof PreviewListPageRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  PreviewIndexRoute: typeof PreviewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/': {
      id: '/preview/'
      path: '/preview'
      fullPath: '/preview/'
      preLoaderRoute: typeof PreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/list-page': {
      id: '/preview/list-page'
      path: '/preview/list-page'
      fullPath: '/preview/list-page'
      preLoaderRoute: typeof PreviewListPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/dashboard': {
      id: '/preview/dashboard'
      path: '/preview/dashboard'
      fullPath: '/preview/dashboard'
      preLoaderRoute: typeof PreviewDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreviewDashboardRoute: PreviewDashboardRoute,
  PreviewListPageRoute: PreviewListPageRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  PreviewIndexRoute: PreviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
